/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const RiskLevel = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const RiskScoreEntry = IDL.Record({
  'id' : IDL.Nat,
  'bmi' : IDL.Float64,
  'userId' : UserId,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'factors' : IDL.Vec(IDL.Text),
  'riskLevel' : RiskLevel,
});
export const SymptomEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'symptomsText' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : IDL.Nat,
  'remedies' : IDL.Vec(IDL.Text),
});
export const MoodEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'note' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const MoodSummary = IDL.Record({
  'period' : IDL.Text,
  'entries' : IDL.Vec(MoodEntry),
  'averageScore' : IDL.Float64,
});
export const MedicalCondition = IDL.Variant({
  'none' : IDL.Null,
  'pcod' : IDL.Null,
  'thyroid' : IDL.Null,
  'obesity' : IDL.Null,
  'diabetes' : IDL.Null,
});
export const DietRecommendation = IDL.Record({
  'tips' : IDL.Vec(IDL.Text),
  'sevenDayPlan' : IDL.Vec(IDL.Vec(IDL.Text)),
  'avoidFoods' : IDL.Vec(IDL.Text),
  'recommendedFoods' : IDL.Vec(IDL.Text),
  'condition' : MedicalCondition,
});
export const HealthReport = IDL.Record({
  'userId' : UserId,
  'recentSymptoms' : IDL.Vec(SymptomEntry),
  'generatedAt' : Timestamp,
  'moodSummary' : MoodSummary,
  'dietRecommendation' : IDL.Opt(DietRecommendation),
  'dailyTip' : IDL.Text,
  'calorieSummaryText' : IDL.Text,
  'latestRiskScore' : IDL.Opt(RiskScoreEntry),
});
export const PortionSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const MealFoodEntry = IDL.Record({
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'gramsEstimate' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'foodItemId' : IDL.Nat,
  'sugar' : IDL.Float64,
  'portionSize' : PortionSize,
  'foodName' : IDL.Text,
  'protein' : IDL.Float64,
});
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const Meal = IDL.Record({
  'id' : IDL.Nat,
  'foods' : IDL.Vec(MealFoodEntry),
  'userId' : UserId,
  'totalCarbs' : IDL.Float64,
  'note' : IDL.Text,
  'totalFat' : IDL.Float64,
  'totalCalories' : IDL.Float64,
  'totalProtein' : IDL.Float64,
  'timestamp' : Timestamp,
  'mealType' : MealType,
});
export const DailyCalorieSummary = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'date' : IDL.Text,
  'goal' : IDL.Nat,
  'remainingCalories' : IDL.Float64,
  'totalCalories' : IDL.Float64,
  'percentageUsed' : IDL.Float64,
});
export const ExerciseItem = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'exerciseType' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'condition' : MedicalCondition,
});
export const NutritionPer100g = IDL.Record({
  'fatG' : IDL.Float64,
  'fiberG' : IDL.Float64,
  'sugarG' : IDL.Float64,
  'caloriesPer100g' : IDL.Float64,
  'carbsG' : IDL.Float64,
  'proteinG' : IDL.Float64,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'isIndian' : IDL.Bool,
  'nutrition' : NutritionPer100g,
});
export const HistoryCategory = IDL.Variant({
  'symptom' : IDL.Null,
  'meal' : IDL.Null,
  'mood' : IDL.Null,
  'riskScore' : IDL.Null,
});
export const HistoryEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : UserId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'category' : HistoryCategory,
});
export const BasicInfo = IDL.Record({
  'username' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const ActivityLevel = IDL.Variant({
  'active' : IDL.Null,
  'veryActive' : IDL.Null,
  'light' : IDL.Null,
  'sedentary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const DietType = IDL.Variant({
  'vegan' : IDL.Null,
  'nonVegetarian' : IDL.Null,
  'eggetarian' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const HealthProfile = IDL.Record({
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'medicalConditions' : IDL.Vec(MedicalCondition),
  'weightKg' : IDL.Float64,
  'dietType' : DietType,
  'dailyCalorieGoal' : IDL.Nat,
});
export const LifestyleHabits = IDL.Record({
  'stressLevel' : IDL.Nat,
  'fitnessGoals' : IDL.Text,
  'sleepHoursPerNight' : IDL.Float64,
  'smokingStatus' : IDL.Bool,
  'alcoholConsumption' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'basicInfo' : BasicInfo,
  'createdAt' : Timestamp,
  'lastLogin' : Timestamp,
  'healthProfile' : IDL.Opt(HealthProfile),
  'registrationStep' : IDL.Nat,
  'lifestyle' : IDL.Opt(LifestyleHabits),
});
export const WeeklySummary = IDL.Record({
  'weekEnd' : IDL.Text,
  'averageDailyCalories' : IDL.Float64,
  'totalCalories' : IDL.Float64,
  'dailySummaries' : IDL.Vec(DailyCalorieSummary),
  'weekStart' : IDL.Text,
});
export const AddMealRequest = IDL.Record({
  'foods' : IDL.Vec(MealFoodEntry),
  'note' : IDL.Text,
  'mealType' : MealType,
});
export const LoginRequest = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const RegisterStep1Request = IDL.Record({
  'username' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const RegisterStep2Request = IDL.Record({
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'heightCm' : IDL.Float64,
  'medicalConditions' : IDL.Vec(MedicalCondition),
  'weightKg' : IDL.Float64,
  'dietType' : DietType,
  'dailyCalorieGoal' : IDL.Nat,
});
export const RegisterStep3Request = IDL.Record({
  'stressLevel' : IDL.Nat,
  'fitnessGoals' : IDL.Text,
  'sleepHoursPerNight' : IDL.Float64,
  'smokingStatus' : IDL.Bool,
  'alcoholConsumption' : IDL.Bool,
});

export const idlService = IDL.Service({
  'calculateRiskScore' : IDL.Func([], [RiskScoreEntry], []),
  'checkSymptoms' : IDL.Func([IDL.Text], [SymptomEntry], []),
  'deleteMeal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateHealthReport' : IDL.Func([], [HealthReport], []),
  'getDailySummary' : IDL.Func([IDL.Text], [DailyCalorieSummary], ['query']),
  'getDailyTip' : IDL.Func([], [IDL.Text], ['query']),
  'getDietRecommendation' : IDL.Func(
      [],
      [IDL.Vec(DietRecommendation)],
      ['query'],
    ),
  'getExercises' : IDL.Func([], [IDL.Vec(ExerciseItem)], ['query']),
  'getExercisesByCondition' : IDL.Func(
      [MedicalCondition],
      [IDL.Vec(ExerciseItem)],
      ['query'],
    ),
  'getFoodById' : IDL.Func([IDL.Nat], [IDL.Opt(FoodItem)], ['query']),
  'getHealthHistory' : IDL.Func(
      [IDL.Opt(HistoryCategory), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(HistoryEvent)],
      ['query'],
    ),
  'getLatestRiskScore' : IDL.Func([], [IDL.Opt(RiskScoreEntry)], ['query']),
  'getMealHistory' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Meal)], ['query']),
  'getMealsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Meal)], ['query']),
  'getMoodEntries' : IDL.Func([IDL.Text], [MoodSummary], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSymptomHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SymptomEntry)],
      ['query'],
    ),
  'getWeeklySummary' : IDL.Func([IDL.Text], [WeeklySummary], ['query']),
  'listFoods' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(FoodItem)], ['query']),
  'logMeal' : IDL.Func([AddMealRequest], [Meal], []),
  'logMood' : IDL.Func([IDL.Nat, IDL.Text], [MoodEntry], []),
  'login' : IDL.Func([LoginRequest], [AuthResult], []),
  'registerStep1' : IDL.Func([RegisterStep1Request], [AuthResult], []),
  'registerStep2' : IDL.Func([RegisterStep2Request], [AuthResult], []),
  'registerStep3' : IDL.Func([RegisterStep3Request], [AuthResult], []),
  'searchFoods' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'setCalorieGoal' : IDL.Func([IDL.Nat], [AuthResult], []),
  'updateHealthProfile' : IDL.Func([RegisterStep2Request], [AuthResult], []),
  'updateLifestyle' : IDL.Func([RegisterStep3Request], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const RiskLevel = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const RiskScoreEntry = IDL.Record({
    'id' : IDL.Nat,
    'bmi' : IDL.Float64,
    'userId' : UserId,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'factors' : IDL.Vec(IDL.Text),
    'riskLevel' : RiskLevel,
  });
  const SymptomEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'symptomsText' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : IDL.Nat,
    'remedies' : IDL.Vec(IDL.Text),
  });
  const MoodEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'note' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const MoodSummary = IDL.Record({
    'period' : IDL.Text,
    'entries' : IDL.Vec(MoodEntry),
    'averageScore' : IDL.Float64,
  });
  const MedicalCondition = IDL.Variant({
    'none' : IDL.Null,
    'pcod' : IDL.Null,
    'thyroid' : IDL.Null,
    'obesity' : IDL.Null,
    'diabetes' : IDL.Null,
  });
  const DietRecommendation = IDL.Record({
    'tips' : IDL.Vec(IDL.Text),
    'sevenDayPlan' : IDL.Vec(IDL.Vec(IDL.Text)),
    'avoidFoods' : IDL.Vec(IDL.Text),
    'recommendedFoods' : IDL.Vec(IDL.Text),
    'condition' : MedicalCondition,
  });
  const HealthReport = IDL.Record({
    'userId' : UserId,
    'recentSymptoms' : IDL.Vec(SymptomEntry),
    'generatedAt' : Timestamp,
    'moodSummary' : MoodSummary,
    'dietRecommendation' : IDL.Opt(DietRecommendation),
    'dailyTip' : IDL.Text,
    'calorieSummaryText' : IDL.Text,
    'latestRiskScore' : IDL.Opt(RiskScoreEntry),
  });
  const PortionSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MealFoodEntry = IDL.Record({
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'gramsEstimate' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'foodItemId' : IDL.Nat,
    'sugar' : IDL.Float64,
    'portionSize' : PortionSize,
    'foodName' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const Meal = IDL.Record({
    'id' : IDL.Nat,
    'foods' : IDL.Vec(MealFoodEntry),
    'userId' : UserId,
    'totalCarbs' : IDL.Float64,
    'note' : IDL.Text,
    'totalFat' : IDL.Float64,
    'totalCalories' : IDL.Float64,
    'totalProtein' : IDL.Float64,
    'timestamp' : Timestamp,
    'mealType' : MealType,
  });
  const DailyCalorieSummary = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'date' : IDL.Text,
    'goal' : IDL.Nat,
    'remainingCalories' : IDL.Float64,
    'totalCalories' : IDL.Float64,
    'percentageUsed' : IDL.Float64,
  });
  const ExerciseItem = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'exerciseType' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'condition' : MedicalCondition,
  });
  const NutritionPer100g = IDL.Record({
    'fatG' : IDL.Float64,
    'fiberG' : IDL.Float64,
    'sugarG' : IDL.Float64,
    'caloriesPer100g' : IDL.Float64,
    'carbsG' : IDL.Float64,
    'proteinG' : IDL.Float64,
  });
  const FoodItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'isIndian' : IDL.Bool,
    'nutrition' : NutritionPer100g,
  });
  const HistoryCategory = IDL.Variant({
    'symptom' : IDL.Null,
    'meal' : IDL.Null,
    'mood' : IDL.Null,
    'riskScore' : IDL.Null,
  });
  const HistoryEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : UserId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'category' : HistoryCategory,
  });
  const BasicInfo = IDL.Record({
    'username' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const ActivityLevel = IDL.Variant({
    'active' : IDL.Null,
    'veryActive' : IDL.Null,
    'light' : IDL.Null,
    'sedentary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const DietType = IDL.Variant({
    'vegan' : IDL.Null,
    'nonVegetarian' : IDL.Null,
    'eggetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const HealthProfile = IDL.Record({
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'medicalConditions' : IDL.Vec(MedicalCondition),
    'weightKg' : IDL.Float64,
    'dietType' : DietType,
    'dailyCalorieGoal' : IDL.Nat,
  });
  const LifestyleHabits = IDL.Record({
    'stressLevel' : IDL.Nat,
    'fitnessGoals' : IDL.Text,
    'sleepHoursPerNight' : IDL.Float64,
    'smokingStatus' : IDL.Bool,
    'alcoholConsumption' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'basicInfo' : BasicInfo,
    'createdAt' : Timestamp,
    'lastLogin' : Timestamp,
    'healthProfile' : IDL.Opt(HealthProfile),
    'registrationStep' : IDL.Nat,
    'lifestyle' : IDL.Opt(LifestyleHabits),
  });
  const WeeklySummary = IDL.Record({
    'weekEnd' : IDL.Text,
    'averageDailyCalories' : IDL.Float64,
    'totalCalories' : IDL.Float64,
    'dailySummaries' : IDL.Vec(DailyCalorieSummary),
    'weekStart' : IDL.Text,
  });
  const AddMealRequest = IDL.Record({
    'foods' : IDL.Vec(MealFoodEntry),
    'note' : IDL.Text,
    'mealType' : MealType,
  });
  const LoginRequest = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const RegisterStep1Request = IDL.Record({
    'username' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const RegisterStep2Request = IDL.Record({
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'heightCm' : IDL.Float64,
    'medicalConditions' : IDL.Vec(MedicalCondition),
    'weightKg' : IDL.Float64,
    'dietType' : DietType,
    'dailyCalorieGoal' : IDL.Nat,
  });
  const RegisterStep3Request = IDL.Record({
    'stressLevel' : IDL.Nat,
    'fitnessGoals' : IDL.Text,
    'sleepHoursPerNight' : IDL.Float64,
    'smokingStatus' : IDL.Bool,
    'alcoholConsumption' : IDL.Bool,
  });
  
  return IDL.Service({
    'calculateRiskScore' : IDL.Func([], [RiskScoreEntry], []),
    'checkSymptoms' : IDL.Func([IDL.Text], [SymptomEntry], []),
    'deleteMeal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateHealthReport' : IDL.Func([], [HealthReport], []),
    'getDailySummary' : IDL.Func([IDL.Text], [DailyCalorieSummary], ['query']),
    'getDailyTip' : IDL.Func([], [IDL.Text], ['query']),
    'getDietRecommendation' : IDL.Func(
        [],
        [IDL.Vec(DietRecommendation)],
        ['query'],
      ),
    'getExercises' : IDL.Func([], [IDL.Vec(ExerciseItem)], ['query']),
    'getExercisesByCondition' : IDL.Func(
        [MedicalCondition],
        [IDL.Vec(ExerciseItem)],
        ['query'],
      ),
    'getFoodById' : IDL.Func([IDL.Nat], [IDL.Opt(FoodItem)], ['query']),
    'getHealthHistory' : IDL.Func(
        [IDL.Opt(HistoryCategory), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(HistoryEvent)],
        ['query'],
      ),
    'getLatestRiskScore' : IDL.Func([], [IDL.Opt(RiskScoreEntry)], ['query']),
    'getMealHistory' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Meal)], ['query']),
    'getMealsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Meal)], ['query']),
    'getMoodEntries' : IDL.Func([IDL.Text], [MoodSummary], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSymptomHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SymptomEntry)],
        ['query'],
      ),
    'getWeeklySummary' : IDL.Func([IDL.Text], [WeeklySummary], ['query']),
    'listFoods' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(FoodItem)], ['query']),
    'logMeal' : IDL.Func([AddMealRequest], [Meal], []),
    'logMood' : IDL.Func([IDL.Nat, IDL.Text], [MoodEntry], []),
    'login' : IDL.Func([LoginRequest], [AuthResult], []),
    'registerStep1' : IDL.Func([RegisterStep1Request], [AuthResult], []),
    'registerStep2' : IDL.Func([RegisterStep2Request], [AuthResult], []),
    'registerStep3' : IDL.Func([RegisterStep3Request], [AuthResult], []),
    'searchFoods' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'setCalorieGoal' : IDL.Func([IDL.Nat], [AuthResult], []),
    'updateHealthProfile' : IDL.Func([RegisterStep2Request], [AuthResult], []),
    'updateLifestyle' : IDL.Func([RegisterStep3Request], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };