/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'active' : null } |
  { 'veryActive' : null } |
  { 'light' : null } |
  { 'sedentary' : null } |
  { 'moderate' : null };
export interface AddMealRequest {
  'foods' : Array<MealFoodEntry>,
  'note' : string,
  'mealType' : MealType,
}
export type AuthResult = { 'ok' : UserProfile } |
  { 'err' : string };
export interface BasicInfo {
  'username' : string,
  'dateOfBirth' : string,
  'fullName' : string,
  'email' : string,
  'gender' : string,
  'passwordHash' : string,
}
export interface DailyCalorieSummary {
  'meals' : Array<Meal>,
  'date' : string,
  'goal' : bigint,
  'remainingCalories' : number,
  'totalCalories' : number,
  'percentageUsed' : number,
}
export interface DietRecommendation {
  'tips' : Array<string>,
  'sevenDayPlan' : Array<Array<string>>,
  'avoidFoods' : Array<string>,
  'recommendedFoods' : Array<string>,
  'condition' : MedicalCondition,
}
export type DietType = { 'vegan' : null } |
  { 'nonVegetarian' : null } |
  { 'eggetarian' : null } |
  { 'vegetarian' : null };
export interface ExerciseItem {
  'id' : bigint,
  'difficultyLevel' : string,
  'title' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'exerciseType' : string,
  'youtubeUrl' : string,
  'condition' : MedicalCondition,
}
export interface FoodItem {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'isIndian' : boolean,
  'nutrition' : NutritionPer100g,
}
export interface HealthProfile {
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'medicalConditions' : Array<MedicalCondition>,
  'weightKg' : number,
  'dietType' : DietType,
  'dailyCalorieGoal' : bigint,
}
export interface HealthReport {
  'userId' : UserId,
  'recentSymptoms' : Array<SymptomEntry>,
  'generatedAt' : Timestamp,
  'moodSummary' : MoodSummary,
  'dietRecommendation' : [] | [DietRecommendation],
  'dailyTip' : string,
  'calorieSummaryText' : string,
  'latestRiskScore' : [] | [RiskScoreEntry],
}
export type HistoryCategory = { 'symptom' : null } |
  { 'meal' : null } |
  { 'mood' : null } |
  { 'riskScore' : null };
export interface HistoryEvent {
  'id' : bigint,
  'title' : string,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
  'category' : HistoryCategory,
}
export interface LifestyleHabits {
  'stressLevel' : bigint,
  'fitnessGoals' : string,
  'sleepHoursPerNight' : number,
  'smokingStatus' : boolean,
  'alcoholConsumption' : boolean,
}
export interface LoginRequest { 'password' : string, 'email' : string }
export interface Meal {
  'id' : bigint,
  'foods' : Array<MealFoodEntry>,
  'userId' : UserId,
  'totalCarbs' : number,
  'note' : string,
  'totalFat' : number,
  'totalCalories' : number,
  'totalProtein' : number,
  'timestamp' : Timestamp,
  'mealType' : MealType,
}
export interface MealFoodEntry {
  'fat' : number,
  'fiber' : number,
  'gramsEstimate' : number,
  'carbs' : number,
  'calories' : number,
  'foodItemId' : bigint,
  'sugar' : number,
  'portionSize' : PortionSize,
  'foodName' : string,
  'protein' : number,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export type MedicalCondition = { 'none' : null } |
  { 'pcod' : null } |
  { 'thyroid' : null } |
  { 'obesity' : null } |
  { 'diabetes' : null };
export interface MoodEntry {
  'id' : bigint,
  'userId' : UserId,
  'note' : string,
  'score' : bigint,
  'timestamp' : Timestamp,
}
export interface MoodSummary {
  'period' : string,
  'entries' : Array<MoodEntry>,
  'averageScore' : number,
}
export interface NutritionPer100g {
  'fatG' : number,
  'fiberG' : number,
  'sugarG' : number,
  'caloriesPer100g' : number,
  'carbsG' : number,
  'proteinG' : number,
}
export type PortionSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface RegisterStep1Request {
  'username' : string,
  'dateOfBirth' : string,
  'fullName' : string,
  'email' : string,
  'gender' : string,
  'passwordHash' : string,
}
export interface RegisterStep2Request {
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'heightCm' : number,
  'medicalConditions' : Array<MedicalCondition>,
  'weightKg' : number,
  'dietType' : DietType,
  'dailyCalorieGoal' : bigint,
}
export interface RegisterStep3Request {
  'stressLevel' : bigint,
  'fitnessGoals' : string,
  'sleepHoursPerNight' : number,
  'smokingStatus' : boolean,
  'alcoholConsumption' : boolean,
}
export type RiskLevel = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface RiskScoreEntry {
  'id' : bigint,
  'bmi' : number,
  'userId' : UserId,
  'score' : bigint,
  'timestamp' : Timestamp,
  'factors' : Array<string>,
  'riskLevel' : RiskLevel,
}
export interface SymptomEntry {
  'id' : bigint,
  'userId' : UserId,
  'symptomsText' : string,
  'timestamp' : Timestamp,
  'severity' : bigint,
  'remedies' : Array<string>,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'basicInfo' : BasicInfo,
  'createdAt' : Timestamp,
  'lastLogin' : Timestamp,
  'healthProfile' : [] | [HealthProfile],
  'registrationStep' : bigint,
  'lifestyle' : [] | [LifestyleHabits],
}
export interface WeeklySummary {
  'weekEnd' : string,
  'averageDailyCalories' : number,
  'totalCalories' : number,
  'dailySummaries' : Array<DailyCalorieSummary>,
  'weekStart' : string,
}
export interface _SERVICE {
  'calculateRiskScore' : ActorMethod<[], RiskScoreEntry>,
  'checkSymptoms' : ActorMethod<[string], SymptomEntry>,
  'deleteMeal' : ActorMethod<[bigint], boolean>,
  'generateHealthReport' : ActorMethod<[], HealthReport>,
  'getDailySummary' : ActorMethod<[string], DailyCalorieSummary>,
  'getDailyTip' : ActorMethod<[], string>,
  'getDietRecommendation' : ActorMethod<[], Array<DietRecommendation>>,
  'getExercises' : ActorMethod<[], Array<ExerciseItem>>,
  'getExercisesByCondition' : ActorMethod<
    [MedicalCondition],
    Array<ExerciseItem>
  >,
  'getFoodById' : ActorMethod<[bigint], [] | [FoodItem]>,
  'getHealthHistory' : ActorMethod<
    [[] | [HistoryCategory], [] | [bigint], [] | [bigint]],
    Array<HistoryEvent>
  >,
  'getLatestRiskScore' : ActorMethod<[], [] | [RiskScoreEntry]>,
  'getMealHistory' : ActorMethod<[bigint, bigint], Array<Meal>>,
  'getMealsForDate' : ActorMethod<[string], Array<Meal>>,
  'getMoodEntries' : ActorMethod<[string], MoodSummary>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSymptomHistory' : ActorMethod<[bigint, bigint], Array<SymptomEntry>>,
  'getWeeklySummary' : ActorMethod<[string], WeeklySummary>,
  'listFoods' : ActorMethod<[bigint, bigint], Array<FoodItem>>,
  'logMeal' : ActorMethod<[AddMealRequest], Meal>,
  'logMood' : ActorMethod<[bigint, string], MoodEntry>,
  'login' : ActorMethod<[LoginRequest], AuthResult>,
  'registerStep1' : ActorMethod<[RegisterStep1Request], AuthResult>,
  'registerStep2' : ActorMethod<[RegisterStep2Request], AuthResult>,
  'registerStep3' : ActorMethod<[RegisterStep3Request], AuthResult>,
  'searchFoods' : ActorMethod<[string], Array<FoodItem>>,
  'setCalorieGoal' : ActorMethod<[bigint], AuthResult>,
  'updateHealthProfile' : ActorMethod<[RegisterStep2Request], AuthResult>,
  'updateLifestyle' : ActorMethod<[RegisterStep3Request], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];