/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BasicInfo {
    username: string;
    dateOfBirth: string;
    fullName: string;
    email: string;
    gender: string;
    passwordHash: string;
}
export interface MoodEntry {
    id: bigint;
    userId: UserId;
    note: string;
    score: bigint;
    timestamp: Timestamp;
}
export interface WeeklySummary {
    weekEnd: string;
    averageDailyCalories: number;
    totalCalories: number;
    dailySummaries: Array<DailyCalorieSummary>;
    weekStart: string;
}
export interface RegisterStep2Request {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    medicalConditions: Array<MedicalCondition>;
    weightKg: number;
    dietType: DietType;
    dailyCalorieGoal: bigint;
}
export interface RegisterStep3Request {
    stressLevel: bigint;
    fitnessGoals: string;
    sleepHoursPerNight: number;
    smokingStatus: boolean;
    alcoholConsumption: boolean;
}
export interface NutritionPer100g {
    fatG: number;
    fiberG: number;
    sugarG: number;
    caloriesPer100g: number;
    carbsG: number;
    proteinG: number;
}
export interface FoodItem {
    id: bigint;
    name: string;
    category: string;
    isIndian: boolean;
    nutrition: NutritionPer100g;
}
export interface DailyCalorieSummary {
    meals: Array<Meal>;
    date: string;
    goal: bigint;
    remainingCalories: number;
    totalCalories: number;
    percentageUsed: number;
}
export type AuthResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface Meal {
    id: bigint;
    foods: Array<MealFoodEntry>;
    userId: UserId;
    totalCarbs: number;
    note: string;
    totalFat: number;
    totalCalories: number;
    totalProtein: number;
    timestamp: Timestamp;
    mealType: MealType;
}
export interface LoginRequest {
    password: string;
    email: string;
}
export interface ExerciseItem {
    id: bigint;
    difficultyLevel: string;
    title: string;
    description: string;
    durationMinutes: bigint;
    exerciseType: string;
    youtubeUrl: string;
    condition: MedicalCondition;
}
export interface DietRecommendation {
    tips: Array<string>;
    sevenDayPlan: Array<Array<string>>;
    avoidFoods: Array<string>;
    recommendedFoods: Array<string>;
    condition: MedicalCondition;
}
export interface HealthReport {
    userId: UserId;
    recentSymptoms: Array<SymptomEntry>;
    generatedAt: Timestamp;
    moodSummary: MoodSummary;
    dietRecommendation?: DietRecommendation;
    dailyTip: string;
    calorieSummaryText: string;
    latestRiskScore?: RiskScoreEntry;
}
export interface SymptomEntry {
    id: bigint;
    userId: UserId;
    symptomsText: string;
    timestamp: Timestamp;
    severity: bigint;
    remedies: Array<string>;
}
export interface RegisterStep1Request {
    username: string;
    dateOfBirth: string;
    fullName: string;
    email: string;
    gender: string;
    passwordHash: string;
}
export interface HealthProfile {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    medicalConditions: Array<MedicalCondition>;
    weightKg: number;
    dietType: DietType;
    dailyCalorieGoal: bigint;
}
export interface HistoryEvent {
    id: bigint;
    title: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    category: HistoryCategory;
}
export interface RiskScoreEntry {
    id: bigint;
    bmi: number;
    userId: UserId;
    score: bigint;
    timestamp: Timestamp;
    factors: Array<string>;
    riskLevel: RiskLevel;
}
export type UserId = Principal;
export interface LifestyleHabits {
    stressLevel: bigint;
    fitnessGoals: string;
    sleepHoursPerNight: number;
    smokingStatus: boolean;
    alcoholConsumption: boolean;
}
export interface AddMealRequest {
    foods: Array<MealFoodEntry>;
    note: string;
    mealType: MealType;
}
export interface MoodSummary {
    period: string;
    entries: Array<MoodEntry>;
    averageScore: number;
}
export interface MealFoodEntry {
    fat: number;
    fiber: number;
    gramsEstimate: number;
    carbs: number;
    calories: number;
    foodItemId: bigint;
    sugar: number;
    portionSize: PortionSize;
    foodName: string;
    protein: number;
}
export interface UserProfile {
    id: UserId;
    basicInfo: BasicInfo;
    createdAt: Timestamp;
    lastLogin: Timestamp;
    healthProfile?: HealthProfile;
    registrationStep: bigint;
    lifestyle?: LifestyleHabits;
}
export enum ActivityLevel {
    active = "active",
    veryActive = "veryActive",
    light = "light",
    sedentary = "sedentary",
    moderate = "moderate"
}
export enum DietType {
    vegan = "vegan",
    nonVegetarian = "nonVegetarian",
    eggetarian = "eggetarian",
    vegetarian = "vegetarian"
}
export enum HistoryCategory {
    symptom = "symptom",
    meal = "meal",
    mood = "mood",
    riskScore = "riskScore"
}
export enum MealType {
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export enum MedicalCondition {
    none = "none",
    pcod = "pcod",
    thyroid = "thyroid",
    obesity = "obesity",
    diabetes = "diabetes"
}
export enum PortionSize {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum RiskLevel {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export interface backendInterface {
    calculateRiskScore(): Promise<RiskScoreEntry>;
    checkSymptoms(symptomsText: string): Promise<SymptomEntry>;
    deleteMeal(mealId: bigint): Promise<boolean>;
    generateHealthReport(): Promise<HealthReport>;
    getDailySummary(date: string): Promise<DailyCalorieSummary>;
    getDailyTip(): Promise<string>;
    getDietRecommendation(): Promise<Array<DietRecommendation>>;
    getExercises(): Promise<Array<ExerciseItem>>;
    getExercisesByCondition(condition: MedicalCondition): Promise<Array<ExerciseItem>>;
    getFoodById(id: bigint): Promise<FoodItem | null>;
    getHealthHistory(categoryFilter: HistoryCategory | null, fromTs: bigint | null, toTs: bigint | null): Promise<Array<HistoryEvent>>;
    getLatestRiskScore(): Promise<RiskScoreEntry | null>;
    getMealHistory(offset: bigint, limit: bigint): Promise<Array<Meal>>;
    getMealsForDate(date: string): Promise<Array<Meal>>;
    getMoodEntries(period: string): Promise<MoodSummary>;
    getMyProfile(): Promise<UserProfile | null>;
    getSymptomHistory(offset: bigint, limit: bigint): Promise<Array<SymptomEntry>>;
    getWeeklySummary(weekStart: string): Promise<WeeklySummary>;
    listFoods(offset: bigint, limit: bigint): Promise<Array<FoodItem>>;
    logMeal(req: AddMealRequest): Promise<Meal>;
    logMood(score: bigint, note: string): Promise<MoodEntry>;
    login(req: LoginRequest): Promise<AuthResult>;
    registerStep1(req: RegisterStep1Request): Promise<AuthResult>;
    registerStep2(req: RegisterStep2Request): Promise<AuthResult>;
    registerStep3(req: RegisterStep3Request): Promise<AuthResult>;
    searchFoods(searchTerm: string): Promise<Array<FoodItem>>;
    setCalorieGoal(goal: bigint): Promise<AuthResult>;
    updateHealthProfile(req: RegisterStep2Request): Promise<AuthResult>;
    updateLifestyle(req: RegisterStep3Request): Promise<AuthResult>;
}
import type { ActivityLevel as _ActivityLevel, AddMealRequest as _AddMealRequest, AuthResult as _AuthResult, BasicInfo as _BasicInfo, DailyCalorieSummary as _DailyCalorieSummary, DietRecommendation as _DietRecommendation, DietType as _DietType, ExerciseItem as _ExerciseItem, FoodItem as _FoodItem, HealthProfile as _HealthProfile, HealthReport as _HealthReport, HistoryCategory as _HistoryCategory, HistoryEvent as _HistoryEvent, LifestyleHabits as _LifestyleHabits, Meal as _Meal, MealFoodEntry as _MealFoodEntry, MealType as _MealType, MedicalCondition as _MedicalCondition, MoodSummary as _MoodSummary, PortionSize as _PortionSize, RegisterStep2Request as _RegisterStep2Request, RiskLevel as _RiskLevel, RiskScoreEntry as _RiskScoreEntry, SymptomEntry as _SymptomEntry, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, WeeklySummary as _WeeklySummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateRiskScore(): Promise<RiskScoreEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateRiskScore();
                return from_candid_RiskScoreEntry_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateRiskScore();
            return from_candid_RiskScoreEntry_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkSymptoms(arg0: string): Promise<SymptomEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSymptoms(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSymptoms(arg0);
            return result;
        }
    }
    async deleteMeal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeal(arg0);
            return result;
        }
    }
    async generateHealthReport(): Promise<HealthReport> {
        if (this.processError) {
            try {
                const result = await this.actor.generateHealthReport();
                return from_candid_HealthReport_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateHealthReport();
            return from_candid_HealthReport_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySummary(arg0: string): Promise<DailyCalorieSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return from_candid_DailyCalorieSummary_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return from_candid_DailyCalorieSummary_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyTip(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTip();
            return result;
        }
    }
    async getDietRecommendation(): Promise<Array<DietRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietRecommendation();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietRecommendation();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercises(): Promise<Array<ExerciseItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercises();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercises();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercisesByCondition(arg0: MedicalCondition): Promise<Array<ExerciseItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByCondition(to_candid_MedicalCondition_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByCondition(to_candid_MedicalCondition_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodById(arg0: bigint): Promise<FoodItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthHistory(arg0: HistoryCategory | null, arg1: bigint | null, arg2: bigint | null): Promise<Array<HistoryEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthHistory(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthHistory(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestRiskScore(): Promise<RiskScoreEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestRiskScore();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestRiskScore();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealHistory(arg0: bigint, arg1: bigint): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealHistory(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealHistory(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealsForDate(arg0: string): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealsForDate(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealsForDate(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodEntries(arg0: string): Promise<MoodSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntries(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSymptomHistory(arg0: bigint, arg1: bigint): Promise<Array<SymptomEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSymptomHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSymptomHistory(arg0, arg1);
            return result;
        }
    }
    async getWeeklySummary(arg0: string): Promise<WeeklySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySummary(arg0);
                return from_candid_WeeklySummary_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySummary(arg0);
            return from_candid_WeeklySummary_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFoods(arg0: bigint, arg1: bigint): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFoods(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFoods(arg0, arg1);
            return result;
        }
    }
    async logMeal(arg0: AddMealRequest): Promise<Meal> {
        if (this.processError) {
            try {
                const result = await this.actor.logMeal(to_candid_AddMealRequest_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Meal_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMeal(to_candid_AddMealRequest_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Meal_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMood(arg0: bigint, arg1: string): Promise<MoodEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.logMood(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMood(arg0, arg1);
            return result;
        }
    }
    async login(arg0: LoginRequest): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStep1(arg0: RegisterStep1Request): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStep1(arg0);
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStep1(arg0);
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStep2(arg0: RegisterStep2Request): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStep2(to_candid_RegisterStep2Request_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStep2(to_candid_RegisterStep2Request_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStep3(arg0: RegisterStep3Request): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStep3(arg0);
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStep3(arg0);
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchFoods(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoods(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoods(arg0);
            return result;
        }
    }
    async setCalorieGoal(arg0: bigint): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setCalorieGoal(arg0);
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCalorieGoal(arg0);
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHealthProfile(arg0: RegisterStep2Request): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHealthProfile(to_candid_RegisterStep2Request_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHealthProfile(to_candid_RegisterStep2Request_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLifestyle(arg0: RegisterStep3Request): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLifestyle(arg0);
                return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLifestyle(arg0);
            return from_candid_AuthResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLevel_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_DailyCalorieSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyCalorieSummary): DailyCalorieSummary {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DietRecommendation_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietRecommendation): DietRecommendation {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DietType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietType): DietType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseItem_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseItem): ExerciseItem {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_HealthProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthProfile): HealthProfile {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_HealthReport_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthReport): HealthReport {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_HistoryCategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoryCategory): HistoryCategory {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_HistoryEvent_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoryEvent): HistoryEvent {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_MealFoodEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealFoodEntry): MealFoodEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MealType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealType): MealType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Meal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meal): Meal {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MedicalCondition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalCondition): MedicalCondition {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PortionSize_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortionSize): PortionSize {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RiskScoreEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskScoreEntry): RiskScoreEntry {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklySummary_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklySummary): WeeklySummary {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiskScoreEntry]): RiskScoreEntry | null {
    return value.length === 0 ? null : from_candid_RiskScoreEntry_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodItem]): FoodItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthProfile]): HealthProfile | null {
    return value.length === 0 ? null : from_candid_HealthProfile_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LifestyleHabits]): LifestyleHabits | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DietRecommendation]): DietRecommendation | null {
    return value.length === 0 ? null : from_candid_DietRecommendation_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<_Meal>;
    date: string;
    goal: bigint;
    remainingCalories: number;
    totalCalories: number;
    percentageUsed: number;
}): {
    meals: Array<Meal>;
    date: string;
    goal: bigint;
    remainingCalories: number;
    totalCalories: number;
    percentageUsed: number;
} {
    return {
        meals: from_candid_vec_n15(_uploadFile, _downloadFile, value.meals),
        date: value.date,
        goal: value.goal,
        remainingCalories: value.remainingCalories,
        totalCalories: value.totalCalories,
        percentageUsed: value.percentageUsed
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    foods: Array<_MealFoodEntry>;
    userId: _UserId;
    totalCarbs: number;
    note: string;
    totalFat: number;
    totalCalories: number;
    totalProtein: number;
    timestamp: _Timestamp;
    mealType: _MealType;
}): {
    id: bigint;
    foods: Array<MealFoodEntry>;
    userId: UserId;
    totalCarbs: number;
    note: string;
    totalFat: number;
    totalCalories: number;
    totalProtein: number;
    timestamp: Timestamp;
    mealType: MealType;
} {
    return {
        id: value.id,
        foods: from_candid_vec_n18(_uploadFile, _downloadFile, value.foods),
        userId: value.userId,
        totalCarbs: value.totalCarbs,
        note: value.note,
        totalFat: value.totalFat,
        totalCalories: value.totalCalories,
        totalProtein: value.totalProtein,
        timestamp: value.timestamp,
        mealType: from_candid_MealType_n23(_uploadFile, _downloadFile, value.mealType)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bmi: number;
    userId: _UserId;
    score: bigint;
    timestamp: _Timestamp;
    factors: Array<string>;
    riskLevel: _RiskLevel;
}): {
    id: bigint;
    bmi: number;
    userId: UserId;
    score: bigint;
    timestamp: Timestamp;
    factors: Array<string>;
    riskLevel: RiskLevel;
} {
    return {
        id: value.id,
        bmi: value.bmi,
        userId: value.userId,
        score: value.score,
        timestamp: value.timestamp,
        factors: value.factors,
        riskLevel: from_candid_RiskLevel_n3(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fat: number;
    fiber: number;
    gramsEstimate: number;
    carbs: number;
    calories: number;
    foodItemId: bigint;
    sugar: number;
    portionSize: _PortionSize;
    foodName: string;
    protein: number;
}): {
    fat: number;
    fiber: number;
    gramsEstimate: number;
    carbs: number;
    calories: number;
    foodItemId: bigint;
    sugar: number;
    portionSize: PortionSize;
    foodName: string;
    protein: number;
} {
    return {
        fat: value.fat,
        fiber: value.fiber,
        gramsEstimate: value.gramsEstimate,
        carbs: value.carbs,
        calories: value.calories,
        foodItemId: value.foodItemId,
        sugar: value.sugar,
        portionSize: from_candid_PortionSize_n21(_uploadFile, _downloadFile, value.portionSize),
        foodName: value.foodName,
        protein: value.protein
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: string;
    title: string;
    description: string;
    durationMinutes: bigint;
    exerciseType: string;
    youtubeUrl: string;
    condition: _MedicalCondition;
}): {
    id: bigint;
    difficultyLevel: string;
    title: string;
    description: string;
    durationMinutes: bigint;
    exerciseType: string;
    youtubeUrl: string;
    condition: MedicalCondition;
} {
    return {
        id: value.id,
        difficultyLevel: value.difficultyLevel,
        title: value.title,
        description: value.description,
        durationMinutes: value.durationMinutes,
        exerciseType: value.exerciseType,
        youtubeUrl: value.youtubeUrl,
        condition: from_candid_MedicalCondition_n10(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: _UserId;
    description: string;
    timestamp: _Timestamp;
    category: _HistoryCategory;
}): {
    id: bigint;
    title: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    category: HistoryCategory;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_HistoryCategory_n39(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    basicInfo: _BasicInfo;
    createdAt: _Timestamp;
    lastLogin: _Timestamp;
    healthProfile: [] | [_HealthProfile];
    registrationStep: bigint;
    lifestyle: [] | [_LifestyleHabits];
}): {
    id: UserId;
    basicInfo: BasicInfo;
    createdAt: Timestamp;
    lastLogin: Timestamp;
    healthProfile?: HealthProfile;
    registrationStep: bigint;
    lifestyle?: LifestyleHabits;
} {
    return {
        id: value.id,
        basicInfo: value.basicInfo,
        createdAt: value.createdAt,
        lastLogin: value.lastLogin,
        healthProfile: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.healthProfile)),
        registrationStep: value.registrationStep,
        lifestyle: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.lifestyle))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    activityLevel: _ActivityLevel;
    heightCm: number;
    medicalConditions: Array<_MedicalCondition>;
    weightKg: number;
    dietType: _DietType;
    dailyCalorieGoal: bigint;
}): {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    medicalConditions: Array<MedicalCondition>;
    weightKg: number;
    dietType: DietType;
    dailyCalorieGoal: bigint;
} {
    return {
        age: value.age,
        activityLevel: from_candid_ActivityLevel_n47(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        medicalConditions: from_candid_vec_n49(_uploadFile, _downloadFile, value.medicalConditions),
        weightKg: value.weightKg,
        dietType: from_candid_DietType_n50(_uploadFile, _downloadFile, value.dietType),
        dailyCalorieGoal: value.dailyCalorieGoal
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weekEnd: string;
    averageDailyCalories: number;
    totalCalories: number;
    dailySummaries: Array<_DailyCalorieSummary>;
    weekStart: string;
}): {
    weekEnd: string;
    averageDailyCalories: number;
    totalCalories: number;
    dailySummaries: Array<DailyCalorieSummary>;
    weekStart: string;
} {
    return {
        weekEnd: value.weekEnd,
        averageDailyCalories: value.averageDailyCalories,
        totalCalories: value.totalCalories,
        dailySummaries: from_candid_vec_n55(_uploadFile, _downloadFile, value.dailySummaries),
        weekStart: value.weekStart
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    recentSymptoms: Array<_SymptomEntry>;
    generatedAt: _Timestamp;
    moodSummary: _MoodSummary;
    dietRecommendation: [] | [_DietRecommendation];
    dailyTip: string;
    calorieSummaryText: string;
    latestRiskScore: [] | [_RiskScoreEntry];
}): {
    userId: UserId;
    recentSymptoms: Array<SymptomEntry>;
    generatedAt: Timestamp;
    moodSummary: MoodSummary;
    dietRecommendation?: DietRecommendation;
    dailyTip: string;
    calorieSummaryText: string;
    latestRiskScore?: RiskScoreEntry;
} {
    return {
        userId: value.userId,
        recentSymptoms: value.recentSymptoms,
        generatedAt: value.generatedAt,
        moodSummary: value.moodSummary,
        dietRecommendation: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dietRecommendation)),
        dailyTip: value.dailyTip,
        calorieSummaryText: value.calorieSummaryText,
        latestRiskScore: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.latestRiskScore))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tips: Array<string>;
    sevenDayPlan: Array<Array<string>>;
    avoidFoods: Array<string>;
    recommendedFoods: Array<string>;
    condition: _MedicalCondition;
}): {
    tips: Array<string>;
    sevenDayPlan: Array<Array<string>>;
    avoidFoods: Array<string>;
    recommendedFoods: Array<string>;
    condition: MedicalCondition;
} {
    return {
        tips: value.tips,
        sevenDayPlan: value.sevenDayPlan,
        avoidFoods: value.avoidFoods,
        recommendedFoods: value.recommendedFoods,
        condition: from_candid_MedicalCondition_n10(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    pcod: null;
} | {
    thyroid: null;
} | {
    obesity: null;
} | {
    diabetes: null;
}): MedicalCondition {
    return "none" in value ? MedicalCondition.none : "pcod" in value ? MedicalCondition.pcod : "thyroid" in value ? MedicalCondition.thyroid : "obesity" in value ? MedicalCondition.obesity : "diabetes" in value ? MedicalCondition.diabetes : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): PortionSize {
    return "large" in value ? PortionSize.large : "small" in value ? PortionSize.small : "medium" in value ? PortionSize.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): MealType {
    return "breakfast" in value ? MealType.breakfast : "lunch" in value ? MealType.lunch : "snack" in value ? MealType.snack : "dinner" in value ? MealType.dinner : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): RiskLevel {
    return "red" in value ? RiskLevel.red : "green" in value ? RiskLevel.green : "yellow" in value ? RiskLevel.yellow : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    symptom: null;
} | {
    meal: null;
} | {
    mood: null;
} | {
    riskScore: null;
}): HistoryCategory {
    return "symptom" in value ? HistoryCategory.symptom : "meal" in value ? HistoryCategory.meal : "mood" in value ? HistoryCategory.mood : "riskScore" in value ? HistoryCategory.riskScore : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
}): ActivityLevel {
    return "active" in value ? ActivityLevel.active : "veryActive" in value ? ActivityLevel.veryActive : "light" in value ? ActivityLevel.light : "sedentary" in value ? ActivityLevel.sedentary : "moderate" in value ? ActivityLevel.moderate : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vegan: null;
} | {
    nonVegetarian: null;
} | {
    eggetarian: null;
} | {
    vegetarian: null;
}): DietType {
    return "vegan" in value ? DietType.vegan : "nonVegetarian" in value ? DietType.nonVegetarian : "eggetarian" in value ? DietType.eggetarian : "vegetarian" in value ? DietType.vegetarian : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meal>): Array<Meal> {
    return value.map((x)=>from_candid_Meal_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MealFoodEntry>): Array<MealFoodEntry> {
    return value.map((x)=>from_candid_MealFoodEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietRecommendation>): Array<DietRecommendation> {
    return value.map((x)=>from_candid_DietRecommendation_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExerciseItem>): Array<ExerciseItem> {
    return value.map((x)=>from_candid_ExerciseItem_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HistoryEvent>): Array<HistoryEvent> {
    return value.map((x)=>from_candid_HistoryEvent_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicalCondition>): Array<MedicalCondition> {
    return value.map((x)=>from_candid_MedicalCondition_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyCalorieSummary>): Array<DailyCalorieSummary> {
    return value.map((x)=>from_candid_DailyCalorieSummary_n13(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_AddMealRequest_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddMealRequest): _AddMealRequest {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_DietType_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): _DietType {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_HistoryCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HistoryCategory): _HistoryCategory {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_MealFoodEntry_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealFoodEntry): _MealFoodEntry {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_MealType_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): _MealType {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_MedicalCondition_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicalCondition): _MedicalCondition {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_PortionSize_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortionSize): _PortionSize {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterStep2Request_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterStep2Request): _RegisterStep2Request {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HistoryCategory | null): [] | [_HistoryCategory] {
    return value === null ? candid_none() : candid_some(to_candid_HistoryCategory_n33(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foods: Array<MealFoodEntry>;
    note: string;
    mealType: MealType;
}): {
    foods: Array<_MealFoodEntry>;
    note: string;
    mealType: _MealType;
} {
    return {
        foods: to_candid_vec_n58(_uploadFile, _downloadFile, value.foods),
        note: value.note,
        mealType: to_candid_MealType_n63(_uploadFile, _downloadFile, value.mealType)
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fat: number;
    fiber: number;
    gramsEstimate: number;
    carbs: number;
    calories: number;
    foodItemId: bigint;
    sugar: number;
    portionSize: PortionSize;
    foodName: string;
    protein: number;
}): {
    fat: number;
    fiber: number;
    gramsEstimate: number;
    carbs: number;
    calories: number;
    foodItemId: bigint;
    sugar: number;
    portionSize: _PortionSize;
    foodName: string;
    protein: number;
} {
    return {
        fat: value.fat,
        fiber: value.fiber,
        gramsEstimate: value.gramsEstimate,
        carbs: value.carbs,
        calories: value.calories,
        foodItemId: value.foodItemId,
        sugar: value.sugar,
        portionSize: to_candid_PortionSize_n61(_uploadFile, _downloadFile, value.portionSize),
        foodName: value.foodName,
        protein: value.protein
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    activityLevel: ActivityLevel;
    heightCm: number;
    medicalConditions: Array<MedicalCondition>;
    weightKg: number;
    dietType: DietType;
    dailyCalorieGoal: bigint;
}): {
    age: bigint;
    activityLevel: _ActivityLevel;
    heightCm: number;
    medicalConditions: Array<_MedicalCondition>;
    weightKg: number;
    dietType: _DietType;
    dailyCalorieGoal: bigint;
} {
    return {
        age: value.age,
        activityLevel: to_candid_ActivityLevel_n69(_uploadFile, _downloadFile, value.activityLevel),
        heightCm: value.heightCm,
        medicalConditions: to_candid_vec_n71(_uploadFile, _downloadFile, value.medicalConditions),
        weightKg: value.weightKg,
        dietType: to_candid_DietType_n72(_uploadFile, _downloadFile, value.dietType),
        dailyCalorieGoal: value.dailyCalorieGoal
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicalCondition): {
    none: null;
} | {
    pcod: null;
} | {
    thyroid: null;
} | {
    obesity: null;
} | {
    diabetes: null;
} {
    return value == MedicalCondition.none ? {
        none: null
    } : value == MedicalCondition.pcod ? {
        pcod: null
    } : value == MedicalCondition.thyroid ? {
        thyroid: null
    } : value == MedicalCondition.obesity ? {
        obesity: null
    } : value == MedicalCondition.diabetes ? {
        diabetes: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HistoryCategory): {
    symptom: null;
} | {
    meal: null;
} | {
    mood: null;
} | {
    riskScore: null;
} {
    return value == HistoryCategory.symptom ? {
        symptom: null
    } : value == HistoryCategory.meal ? {
        meal: null
    } : value == HistoryCategory.mood ? {
        mood: null
    } : value == HistoryCategory.riskScore ? {
        riskScore: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortionSize): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == PortionSize.large ? {
        large: null
    } : value == PortionSize.small ? {
        small: null
    } : value == PortionSize.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealType): {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
} {
    return value == MealType.breakfast ? {
        breakfast: null
    } : value == MealType.lunch ? {
        lunch: null
    } : value == MealType.snack ? {
        snack: null
    } : value == MealType.dinner ? {
        dinner: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
} {
    return value == ActivityLevel.active ? {
        active: null
    } : value == ActivityLevel.veryActive ? {
        veryActive: null
    } : value == ActivityLevel.light ? {
        light: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): {
    vegan: null;
} | {
    nonVegetarian: null;
} | {
    eggetarian: null;
} | {
    vegetarian: null;
} {
    return value == DietType.vegan ? {
        vegan: null
    } : value == DietType.nonVegetarian ? {
        nonVegetarian: null
    } : value == DietType.eggetarian ? {
        eggetarian: null
    } : value == DietType.vegetarian ? {
        vegetarian: null
    } : value;
}
function to_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MealFoodEntry>): Array<_MealFoodEntry> {
    return value.map((x)=>to_candid_MealFoodEntry_n59(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MedicalCondition>): Array<_MedicalCondition> {
    return value.map((x)=>to_candid_MedicalCondition_n29(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
